# -*- coding: utf-8 -*-
"""Live Coding - Random Forest

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DYOz4cGSQwF2C4CHCED6S1JtuIToge6Z
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

"""### 1. Carregamento dos Dados

Vamos carregar o dataset Breast Cancer, que está convenientemente disponível em `sklearn.datasets`. Este dataset contém características de imagens de massa mamária usadas para prever se um tumor é maligno ou benigno.
"""

print("--- 1. DATA LOADING ---")
dataset = load_breast_cancer(as_frame=True)
X = dataset.data   # 30 tumor features (Radius, Perimeter, Texture, etc.)
y = dataset.target # 0 = Malignant, 1 = Benign

print(f"The dataset has {X.shape[0]} patients and {X.shape[1]} features.")
print("Since we have 30 columns, the Forest will be very efficient in exploring all of them!\n")

"""### 2. Divisão Treino / Teste

Para avaliar nossos modelos com precisão, dividimos o dataset em conjuntos de treinamento e teste. Usamos `stratify=y` para garantir que a proporção de tumores benignos e malignos seja mantida em ambos os conjuntos.
"""

print("--- 2. TRAIN / TEST SPLIT ---")
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)
print(f"Train: {X_train.shape[0]} patients | Test: {X_test.shape[0]} patients\n")

"""### 3. A Árvore Solitária (Baseline)

Primeiro, treinamos um único Classificador de Árvore de Decisão como modelo baseline. Isso nos ajudará a entender o desempenho de um modelo menos complexo antes de passarmos para um método de ensemble como a Random Forest.
"""

print("--- 3. THE SOLITARY TREE (BASELINE) ---")
arvore = DecisionTreeClassifier(random_state=42)
arvore.fit(X_train, y_train)

acc_treino_arvore = arvore.score(X_train, y_train)
acc_teste_arvore = arvore.score(X_test, y_test)
print(f"Tree - Train Accuracy: {acc_treino_arvore * 100:.2f}%")
print(f"Tree - Test Accuracy:  {acc_teste_arvore * 100:.2f}%")
print(f"GAP (Overfitting): {(acc_treino_arvore - acc_teste_arvore) * 100:.2f}%\n")

"""### 4. A Random Forest (O Conselho de Médicos)

Em seguida, treinamos um Classificador Random Forest. Este método de ensemble constrói múltiplas árvores de decisão e mescla suas previsões, muitas vezes levando a uma melhor acurácia e redução do overfitting em comparação com uma única árvore de decisão.

- `n_estimators=100`: Cria 100 árvores diferentes.
- `n_jobs=-1`: Utiliza todos os núcleos de CPU disponíveis para processamento paralelo, acelerando o treinamento.
"""

print("--- 4. THE RANDOM FOREST (THE COUNCIL OF DOCTORS) ---")
floresta = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=42)
floresta.fit(X_train, y_train)

acc_treino_rf = floresta.score(X_train, y_train)
acc_teste_rf = floresta.score(X_test, y_test)
print(f"Forest - Train Accuracy: {acc_treino_rf * 100:.2f}%")
print(f"Forest - Test Accuracy:  {acc_teste_rf * 100:.2f}%")
print(f"GAP (Overfitting): {(acc_treino_rf - acc_teste_rf) * 100:.2f}%\n")

"""### 5. Visualização: Quais Características Mais Importam?

Ao contrário de uma rede neural, uma Random Forest pode nos dizer exatamente o que o modelo aprendeu, fornecendo as importâncias das características. Isso nos ajuda a entender quais características do tumor são mais influentes na previsão de sua malignidade.
"""

print("--- 5. VISUALIZATION: WHICH FEATURES MATTER MOST? ---")
importancias = floresta.feature_importances_

df_importancias = pd.DataFrame({
    'Feature': X.columns,
    'Importance': importancias
}).sort_values(by='Importance', ascending=False)

top_10 = df_importancias.head(10)

plt.figure(figsize=(10, 6))
sns.barplot(x='Importance', y='Feature', data=top_10, palette='viridis')
plt.title('Top 10 Decision Factors of the Random Forest (Explainability)', fontsize=14)
plt.xlabel('Relative Importance (Gini Impurity Reduction)')
plt.ylabel('Tumor Characteristic')
plt.tight_layout()
plt.show()

print("\n--- 6. O RAIO-X DA FLORESTA (VISUALIZAÇÃO DO ENSEMBLE) ---")
print("Gerando o gráfico das árvores")

from sklearn.tree import plot_tree

arvores_exemplo = [floresta.estimators_[0], floresta.estimators_[49], floresta.estimators_[99]]

fig, axes = plt.subplots(nrows=1, ncols=3, figsize=(24, 7), dpi=300)
fig.suptitle('Por Dentro da Random Forest: 3 Árvores Votando de Forma Independente', fontsize=18, fontweight='bold', color='#333333')

for i, arvore_individual in enumerate(arvores_exemplo):
    # Usamos max_depth=2 APENAS para a visualização não virar uma teia de aranha ilegível.
    # O modelo original continua profundo, estamos apenas a olhar para o topo das árvores.
    plot_tree(arvore_individual,
              feature_names=X.columns,
              class_names=['Maligno', 'Benigno'],
              filled=True,
              rounded=True,
              max_depth=2,
              ax=axes[i],
              fontsize=9)

    # Destacando o título de cada subplot
    axes[i].set_title(f'Árvore {i+1} da Floresta', fontsize=14, color='#b22222', pad=15)

plt.tight_layout()
# Ajuste manual para o título principal não sobrepor os subplots
plt.subplots_adjust(top=0.85)
plt.show()

print("\n--- 7. ABERTURA DAS URNAS: COMO OCORRE A VOTAÇÃO? ---")

paciente_exemplo = X_test.iloc[[0]]
gabarito_real = y_test.iloc[0]

votos_maligno = 0
votos_benigno = 0

print(f"Paciente Selecionado: Índice 0")
print(f"Diagnóstico Real (Gabarito): {'Benigno (1)' if gabarito_real == 1 else 'Maligno (0)'}\n")

for i, arvore in enumerate(floresta.estimators_):
    voto = arvore.predict(paciente_exemplo.values)[0]

    if voto == 1.0:
        votos_benigno += 1
        voto_str = "Benigno"
    else:
        votos_maligno += 1
        voto_str = "Maligno"

    if i < 5:
        print(f"Árvore {i+1} votou: {voto_str}")

print("... (votação das outras 95 árvores) ...\n")

print("--- RESULTADO DA APURAÇÃO (100 ÁRVORES) ---")
print(f"Votos para Maligno (0): {votos_maligno}")
print(f"Votos para Benigno (1): {votos_benigno}")

previsao_oficial = floresta.predict(paciente_exemplo)[0]
resultado_str = 'Benigno (1)' if previsao_oficial == 1 else 'Maligno (0)'
print(f"=> Decisão final da Floresta: {resultado_str}")

# --- GRÁFICO DE PIZZA DA VOTAÇÃO ---
plt.figure(figsize=(7, 7), dpi=150)
labels = ['Maligno (0)', 'Benigno (1)']
votos = [votos_maligno, votos_benigno]
cores = ['#d9534f', '#6b8e7c'] # Vermelho (Maligno), Verde (Benigno)

# Destacar levemente a fatia vencedora (explode)
explode = (0.1, 0) if votos_maligno > votos_benigno else (0, 0.1)

# Criação do gráfico
plt.pie(votos, explode=explode, labels=labels, colors=cores, autopct='%1.1f%%',
        shadow=True, startangle=140, textprops={'fontsize': 14, 'weight': 'bold'})

plt.title('Votação Democrática da Random Forest\n(Decisão para 1 Paciente Específico)', fontsize=16, fontweight='bold', pad=20)
plt.show()

from sklearn.metrics import confusion_matrix

print("\n--- 8. MATRIZ DE CONFUSÃO (O CUSTO DO ERRO) ---")
# Fazendo as previsões com os dados de teste
y_pred = floresta.predict(X_test)
matriz = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6, 5), dpi=150)
sns.heatmap(matriz, annot=True, fmt='d', cmap='Reds',
            xticklabels=['Maligno (0)', 'Benigno (1)'],
            yticklabels=['Maligno (0)', 'Benigno (1)'],
            annot_kws={"size": 14, "weight": "bold"})

plt.title('Matriz de Confusão - Random Forest', fontsize=14, pad=15)
plt.ylabel('Real (Gabarito)', fontsize=12)
plt.xlabel('Previsão do Modelo', fontsize=12)
plt.tight_layout()
plt.show()